// Copyright (c) 2026, ft_transcendence (https://42.fr) and/or its affiliates. All rights reserved

use std::sync::Mutex;
use actix_web::guard::Guard;
use actix_web::web::Json;
use crate::model::database_initializer::DatabaseInitializer;
use crate::users::{CreateUser, UserInfo};
use diesel::prelude::*;
use diesel::result::Error;
use actix_security::prelude::{Argon2PasswordEncoder, Authenticator, PasswordEncoder, User};
use actix_web::web;

#[derive(Queryable, Selectable, Clone)]
#[diesel(table_name = crate::schema::ftt_users)]
pub struct DbUser {
    pub id: i32,
    pub name: String,
    pub email: String,
    pub password: String,
}

// Used only for INSERT statements — no id field since it is generated by the DB
#[derive(Insertable)]
#[diesel(table_name = crate::schema::ftt_users)]
struct NewUser<'a> {
    name: &'a str,
    email: &'a str,
    password: &'a str,
}

pub enum CreateUserError {
    /// A user with the same name or email already exists
    AlreadyExists,
    /// An unexpected database error occurred
    DatabaseError(diesel::result::Error),
}

impl From<Error> for CreateUserError {
    fn from(e: Error) -> Self {
        CreateUserError::DatabaseError(e)
    }
}

pub fn get_user_from_db_by_name(db: &mut DatabaseInitializer, user_name: String) -> Option<DbUser> {
    use crate::schema::ftt_users::dsl::*;

    let conn = db
        .connection
        .as_mut()
        .expect("Database connection is not established");

    // Reject if name or email is already taken
    ftt_users
        .filter(name.eq(&user_name))
        .select(DbUser::as_select())
        .first(conn)
        .optional().ok()?
}

pub fn get_all_users_from_db(pool: &web::Data<Mutex<DatabaseInitializer>>) -> Option<Vec<DbUser>> {
    use crate::schema::ftt_users::dsl::*;

    let mut db = pool.lock().expect("create_user expect DatabaseInitializer");
    let conn = db
        .connection
        .as_mut()
        .expect("create_user_in_db: Database connection is not established");


    // Reject if name or email is already taken
    ftt_users
        .select(DbUser::as_select())
        .load(conn)
        .optional().ok()?
}

pub fn get_user_from_db_by_name_or_email(conn: &mut PgConnection, user_name: &String, user_email: &String)
    -> Option<DbUser> {
    use crate::schema::ftt_users::dsl::*;

    // Reject if name or email is already taken
    ftt_users
        .filter(name.eq(user_name).or(email.eq(user_email)))
        .select(DbUser::as_select())
        .first(conn)
        .optional().ok()?
}

/// Creates a new user in ftt_users if no existing row shares the same name or email.
/// Returns the created user's info on success, or a `CreateUserError` on failure.
pub fn create_user_in_db(
    db: &mut DatabaseInitializer,
    new_user: &Json<CreateUser>,
    encoder: &Argon2PasswordEncoder,
) -> Result<UserInfo, CreateUserError> {
    use crate::schema::ftt_users::dsl::*;

    let conn = db
        .connection
        .as_mut()
        .expect("create_user_in_db: Database connection is not established");

    // Reject if name or email is already taken
    let existing = get_user_from_db_by_name_or_email(conn, &new_user.name, &new_user.email);

    if existing.is_some() {
        return Err(CreateUserError::AlreadyExists);
    }

    let encoded_password = encoder.encode(&new_user.password);
    // Insert and return the newly created row
    let inserted: DbUser = diesel::insert_into(ftt_users)
        .values(&NewUser {
            name: &new_user.name,
            email: &new_user.email,
            password: &encoded_password.as_str()
        })
        .returning(DbUser::as_returning())
        .get_result(conn)?;

    Ok(UserInfo {
        user_id: inserted.id as u32,
        user_name: inserted.name,
        user_email: inserted.email,
        friends: vec![],
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use actix_security::prelude::{Argon2PasswordEncoder, PasswordEncoder};

    /// Happy path: encoded output is not equal to the raw plaintext.
    #[test]
    fn argon2_encode_does_not_return_plaintext() {
        let encoder = Argon2PasswordEncoder::new();
        let raw = "supersecret";
        let encoded = encoder.encode(raw);
        assert_ne!(raw, encoded, "encoded password must not equal the raw password");
    }

    /// Happy path: encoded password verifies correctly against the raw password.
    #[test]
    fn argon2_encoded_password_matches_raw() {
        let encoder = Argon2PasswordEncoder::new();
        let raw = "supersecret";
        let encoded = encoder.encode(raw);
        assert!(
            encoder.matches(raw, &encoded.as_str()),
            "encoder.matches() must return true for the correct raw password"
        );
    }

    /// Edge case: wrong password does NOT match the stored hash.
    #[test]
    fn argon2_wrong_password_does_not_match() {
        let encoder = Argon2PasswordEncoder::new();
        let encoded = encoder.encode("correct_password");
        assert!(
            !encoder.matches("wrong_password", &encoded.as_str()),
            "encoder.matches() must return false for an incorrect password"
        );
    }

    /// Edge case: empty string encodes and round-trips correctly.
    #[test]
    fn argon2_empty_password_encodes_and_matches() {
        let encoder = Argon2PasswordEncoder::new();
        let encoded = encoder.encode("");
        assert!(encoder.matches("", &encoded.as_str()));
        assert!(!encoder.matches("notempty", &encoded.as_str()));
    }
}

