// Copyright (c) 2026, ft_transcendence (https://42.fr) and/or its affiliates. All rights reserved

use crate::model::database_initializer::DatabaseInitializer;
use crate::users::{CreateUser, UserInfo};
use actix_security::prelude::{Argon2PasswordEncoder, PasswordEncoder};
use diesel::deserialize::{self, FromSql, FromSqlRow};
use diesel::expression::AsExpression;
use diesel::pg::PgValue;
use diesel::prelude::*;
use diesel::serialize::{self, IsNull, Output, ToSql};
use diesel::sql_types::Text;
use std::convert::From;
use std::io::Write;

/// `Vec<i32>` stored in PostgreSQL as a JSON text array (e.g. `[1,2,3]`).
/// Implements Diesel's `FromSql`/`ToSql` so it maps transparently to a TEXT column.
#[derive(Debug, Clone, AsExpression, FromSqlRow)]
#[diesel(sql_type = Text)]
pub struct FriendList(pub Vec<i32>);

impl FromSql<Text, diesel::pg::Pg> for FriendList {
    fn from_sql(bytes: PgValue<'_>) -> deserialize::Result<Self> {
        let s = <String as FromSql<Text, diesel::pg::Pg>>::from_sql(bytes)?;
        let vec: Vec<i32> = serde_json::from_str(&s)
            .map_err(|e| Box::new(e) as Box<dyn std::error::Error + Send + Sync>)?;
        Ok(FriendList(vec))
    }
}

impl ToSql<Text, diesel::pg::Pg> for FriendList {
    fn to_sql<'b>(&'b self, out: &mut Output<'b, '_, diesel::pg::Pg>) -> serialize::Result {
        let s = serde_json::to_string(&self.0)
            .map_err(|e| Box::new(e) as Box<dyn std::error::Error + Send + Sync>)?;
        out.write_all(s.as_bytes())?;
        Ok(IsNull::No)
    }
}

#[derive(Queryable, Selectable, Clone)]
#[diesel(table_name = crate::schema::ftt_users)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct DbUser {
    pub id: i32,
    pub name: String,
    pub email: String,
    pub password: String,
    pub bio: String,
    pub avatar_url: String,
    pub friends: FriendList,
}

impl DbUser {

    #[allow(dead_code)]
    pub fn new(
        id: i32,
        name: String,
        email: String,
        password: String,
        bio: String,
        avatar_url: String,
        friends: Vec<i32>,
    ) -> Self {
        DbUser {
            id,
            name,
            email,
            password,
            bio,
            avatar_url,
            friends: FriendList(friends),
        }
    }
}

// Used only for INSERT statements — no id field since it is generated by the DB.
// bio, avatar_url, friends are intentionally omitted: the DB DEFAULT handles them
// ('', '', '[]') so new registrations start with sensible empty values.
#[derive(Insertable)]
#[diesel(table_name = crate::schema::ftt_users)]
pub struct NewUser<'a> {
    name: &'a str,
    email: &'a str,
    password: &'a str,
}

impl<'a> NewUser<'a> {
    pub fn create(name: &'a str, email: &'a str, password: &'a str) -> Self {
        NewUser {
            name,
            email,
            password,
        }
    }
}

trait UserConversion {
    type UserInfo;

    fn try_into(self) -> Option<Self::UserInfo>;
}

impl From<DbUser> for UserInfo {
    fn from(item: DbUser) -> Self {
        Self {
            id: item.id,
            name: item.name,
            email: item.email,
            bio: item.bio,
            avatar_url: item.avatar_url,
            // status is a runtime value, not persisted — default to offline
            status: "offline".to_string(),
            friends: item.friends.0,
        }
    }
}

impl UserConversion for Option<DbUser> {
    type UserInfo = UserInfo;

    fn try_into(self) -> Option<UserInfo> {
        if let Some(item) = self {
            Some(UserInfo::from(item))
        } else {
            None
        }
    }
}

pub enum CreateUserError {
    /// A user with the same name or email already exists
    AlreadyExists,
    /// An unexpected database error occurred
    DatabaseError(diesel::result::Error),
}

fn connection(db: &mut DatabaseInitializer) -> &mut PgConnection {
    db.connection
        .as_mut()
        .expect("Database connection is not established")
}

pub fn seed_users_in_db(db: &mut DatabaseInitializer) -> Result<(), diesel::result::Error> {
    use crate::schema::ftt_users::dsl::*;
    let encoder = Argon2PasswordEncoder::new();

    let conn = connection(db);
    let test_pwd = encoder.encode("test");
    let admin_pwd = encoder.encode("admin");
    let guest_pwd = encoder.encode("guest");
    let seed_users = [
        ("test", "test@example.local", &test_pwd),
        ("admin", "admin@example.local", &admin_pwd),
        ("guest", "guest@example.local", &guest_pwd),
    ];

    for (seed_name, seed_email, seed_password) in seed_users {
        let existing = ftt_users
            .filter(name.eq(seed_name).or(email.eq(seed_email)))
            .select(id)
            .first::<i32>(conn)
            .optional()?;

        if existing.is_none() {
            diesel::insert_into(ftt_users)
                .values(&NewUser {
                    name: seed_name,
                    email: seed_email,
                    password: &seed_password,
                })
                .execute(conn)?;
        } else {
            diesel::update(ftt_users.filter(name.eq(seed_name)))
                .set(password.eq(&seed_password))
                .execute(conn)?;
        }
    }

    Ok(())
}

pub fn get_all_users_from_db(db: &mut DatabaseInitializer) -> Option<Vec<DbUser>> {
    use crate::schema::ftt_users::dsl::*;

    let conn = connection(db);

    ftt_users
        .select(DbUser::as_select())
        .load(conn)
        .optional()
        .ok()?
}

pub fn list_users_in_db(
    db: &mut DatabaseInitializer,
) -> Result<Vec<UserInfo>, diesel::result::Error> {
    use crate::schema::ftt_users::dsl::*;

    let rows = ftt_users
        .order(id.asc())
        .select(DbUser::as_select())
        .load::<DbUser>(connection(db))?;

    Ok(rows.into_iter().map(UserInfo::from).collect())
}

pub fn get_user_in_db(
    db: &mut DatabaseInitializer,
    user_id: i32,
) -> Result<Option<UserInfo>, diesel::result::Error> {
    use crate::schema::ftt_users::dsl::*;

    let user = ftt_users
        .filter(id.eq(user_id))
        .select(DbUser::as_select())
        .first::<DbUser>(connection(db))
        .optional()?;

    Ok(UserConversion::try_into(user))
}

#[allow(dead_code)]
pub fn login_user_in_db(
    db: &mut DatabaseInitializer,
    login: &DbUser,
) -> Result<Option<UserInfo>, diesel::result::Error> {
    use crate::schema::ftt_users::dsl::*;

    let user = ftt_users
        .filter(name.eq(&login.name).and(password.eq(&login.password)))
        .select(DbUser::as_select())
        .first::<DbUser>(connection(db))
        .optional()?;

    Ok(UserConversion::try_into(user))
}

impl From<diesel::result::Error> for CreateUserError {
    fn from(e: diesel::result::Error) -> Self {
        CreateUserError::DatabaseError(e)
    }
}

/// Creates a new user in ftt_users if no existing row shares the same name or email.
/// Returns the created user's info on success, or a `CreateUserError` on failure.
pub fn create_user_in_db(
    db: &mut DatabaseInitializer,
    new_user: &CreateUser,
    encoder: &Argon2PasswordEncoder,
) -> Result<UserInfo, CreateUserError> {
    use crate::schema::ftt_users::dsl::*;

    let conn = connection(db);

    // Reject if name or email is already taken
    let existing = ftt_users
        .filter(name.eq(&new_user.name).or(email.eq(&new_user.email)))
        .select(DbUser::as_select())
        .first(conn)
        .optional()?;

    if existing.is_some() {
        return Err(CreateUserError::AlreadyExists);
    }

    // Insert and return the newly created row
    let inserted_user: DbUser = diesel::insert_into(ftt_users)
        .values(&NewUser {
            name: &new_user.name,
            email: &new_user.email,
            password: &encoder.encode(&new_user.password),
        })
        .returning(DbUser::as_returning())
        .get_result(conn)?;

    Ok(UserInfo::from(inserted_user))
}

pub fn find_user_id_by_name(
    db: &mut DatabaseInitializer,
    user_name: &str,
) -> Result<Option<i32>, diesel::result::Error> {
    use crate::model::database_initializer;
    use crate::schema::ftt_users::dsl as users;

    users::ftt_users
        .filter(users::name.eq(user_name))
        .select(users::id)
        .first::<i32>(database_initializer::connection(db))
        .optional()
}
