// Copyright (c) 2026, ft_transcendence (https://42.fr) and/or its affiliates. All rights reserved

use actix_web::web::Json;
use crate::model::database_initializer::DatabaseInitializer;
use crate::users::{CreateUser, UserInfo};
use diesel::prelude::*;

// Internal Diesel model mapped to the ftt_users table
#[derive(Queryable, Selectable)]
#[diesel(table_name = crate::schema::ftt_users)]
#[diesel(check_for_backend(diesel::pg::Pg))]
struct User {
    id: i32,
    name: String,
    email: String,
}

// Used only for INSERT statements — no id field since it is generated by the DB
#[derive(Insertable)]
#[diesel(table_name = crate::schema::ftt_users)]
struct NewUser<'a> {
    name: &'a str,
    email: &'a str,
    password: &'a str,
}

pub enum CreateUserError {
    /// A user with the same name or email already exists
    AlreadyExists,
    /// An unexpected database error occurred
    DatabaseError(diesel::result::Error),
}

impl From<diesel::result::Error> for CreateUserError {
    fn from(e: diesel::result::Error) -> Self {
        CreateUserError::DatabaseError(e)
    }
}

/// Creates a new user in ftt_users if no existing row shares the same name or email.
/// Returns the created user's info on success, or a `CreateUserError` on failure.
pub fn create_user_in_db(
    db: &mut DatabaseInitializer,
    new_user: &Json<CreateUser>,
) -> Result<UserInfo, CreateUserError> {
    use crate::schema::ftt_users::dsl::*;

    let conn = db
        .connection
        .as_mut()
        .expect("Database connection is not established");

    // Reject if name or email is already taken
    let existing = ftt_users
        .filter(name.eq(&new_user.name).or(email.eq(&new_user.email)))
        .select(User::as_select())
        .first(conn)
        .optional()?;

    if existing.is_some() {
        return Err(CreateUserError::AlreadyExists);
    }

    // Insert and return the newly created row
    let inserted: User = diesel::insert_into(ftt_users)
        .values(&NewUser {
            name: &new_user.name,
            email: &new_user.email,
            password: &new_user.password
        })
        .returning(User::as_returning())
        .get_result(conn)?;

    Ok(UserInfo {
        user_id: inserted.id as u32,
        user_name: inserted.name,
        user_email: inserted.email,
        friends: vec![],
    })
}
