// Copyright (c) 2026, ft_transcendence (https://42.fr) and/or its affiliates. All rights reserved

use crate::model::database_initializer::{connection, DatabaseInitializer};
use crate::users::{CreateUser, UserInfo};
use actix_security::prelude::{Argon2PasswordEncoder, PasswordEncoder};
use diesel::deserialize::{self, FromSql, FromSqlRow};
use diesel::expression::AsExpression;
use diesel::pg::PgValue;
use diesel::prelude::*;
use diesel::serialize::{self, IsNull, Output, ToSql};
use diesel::sql_types::Text;
use std::convert::From;
use std::io::Write;
use rand::Rng;

/// `Vec<i32>` stored in PostgreSQL as a JSON text array (e.g. `[1,2,3]`).
/// Implements Diesel's `FromSql`/`ToSql` so it maps transparently to a TEXT column.
#[derive(Debug, Clone, AsExpression, FromSqlRow)]
#[diesel(sql_type = Text)]
pub struct FriendList(pub Vec<i32>);

impl FromSql<Text, diesel::pg::Pg> for FriendList {
    fn from_sql(bytes: PgValue<'_>) -> deserialize::Result<Self> {
        let s = <String as FromSql<Text, diesel::pg::Pg>>::from_sql(bytes)?;
        let vec: Vec<i32> = serde_json::from_str(&s)
            .map_err(|e| Box::new(e) as Box<dyn std::error::Error + Send + Sync>)?;
        Ok(FriendList(vec))
    }
}

impl ToSql<Text, diesel::pg::Pg> for FriendList {
    fn to_sql<'b>(&'b self, out: &mut Output<'b, '_, diesel::pg::Pg>) -> serialize::Result {
        let s = serde_json::to_string(&self.0)
            .map_err(|e| Box::new(e) as Box<dyn std::error::Error + Send + Sync>)?;
        out.write_all(s.as_bytes())?;
        Ok(IsNull::No)
    }
}

#[derive(Queryable, Selectable, Clone)]
#[diesel(table_name = crate::schema::ftt_users)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct DbUser {
    pub id: i32,
    pub name: String,
    pub email: String,
    pub password: String,
    pub bio: String,
    pub avatar_url: String,
    pub friends: FriendList,
    pub provider: String,
    pub provider_user_id: String,
}

#[derive(Insertable)]
#[diesel(table_name = crate::schema::ftt_users)]
struct NewOAuthUser<'a> {
    name: &'a str,
    email: &'a str,
    password: &'a str,
    provider: &'a str,
    provider_user_id: &'a str,
}

pub struct OAuthProfile {
    pub provider: String,
    pub provider_user_id: String,
    pub login: String,
    pub email: String,
}

pub fn find_or_create_oauth_user(
    db: &mut DatabaseInitializer,
    profile: &OAuthProfile,
    encoder: &Argon2PasswordEncoder,
    ) -> Result <DbUser, diesel::result::Error> {
    use crate::schema::ftt_users::dsl::*;

    let conn = connection(db);

    let existing = ftt_users
        .filter(
            provider
                .eq(&profile.provider)
                .and(provider_user_id.eq(&profile.provider_user_id)),
        )
        .select(DbUser::as_select())
        .first::<DbUser>(conn)
        .optional()?;

    if let Some(user) = existing {
        // fill in an email we didn't have before (GitHub often gives none on
        // the first login). only ever fills a blank, never overwrites
        if user.email.is_empty() && !profile.email.is_empty() {
            diesel::update(ftt_users.filter(id.eq(user.id)))
                .set(email.eq(&profile.email))
                .execute(conn)?;
            return Ok(DbUser {
                email: profile.email.clone(),
                ..user
            });
        }
        return Ok(user);
    }

    let mut candidate = profile.login.clone();
    let mut attempt = 0;
    while ftt_users
        .filter(name.eq(&candidate))
        .select(id)
        .first::<i32>(conn)
        .optional()?
        .is_some()
    {
        attempt += 1;
        candidate = format!("{}-{}-{}", 
            profile.login, profile.provider, attempt);
    }

    let unreachable_secret: String = rand::thread_rng()
        .sample_iter(&rand::distributions::Alphanumeric)
        .take(48)
        .map(char::from)
        .collect();

    let inserted: DbUser = diesel::insert_into(ftt_users)
        .values(&NewOAuthUser {
            name: &candidate,
            email: &profile.email,
            password: &encoder.encode(&unreachable_secret),
            provider: &profile.provider,
            provider_user_id: &profile.provider_user_id,
        })
        .returning(DbUser::as_returning())
        .get_result(conn)?;

    // the row, not UserInfo — the caller needs `password` for the user store
    Ok(inserted)
}

// Used only for INSERT statements — no id field since it is generated by the DB.
// bio, avatar_url, friends are intentionally omitted: the DB DEFAULT handles them
// ('', '', '[]') so new registrations start with sensible empty values.
#[derive(Insertable)]
#[diesel(table_name = crate::schema::ftt_users)]
pub struct NewUser<'a> {
    name: &'a str,
    email: &'a str,
    password: &'a str,
}

impl From<DbUser> for UserInfo {
    fn from(item: DbUser) -> Self {
        Self {
            id: item.id,
            name: item.name,
            email: item.email,
            bio: item.bio,
            avatar_url: item.avatar_url,
            // status is a runtime value, not persisted — default to offline
            status: "offline".to_string(),
            friends: item.friends.0,
        }
    }
}

pub enum CreateUserError {
    /// A user with the same name or email already exists
    AlreadyExists,
    /// An unexpected database error occurred
    DatabaseError(diesel::result::Error),
}

pub fn seed_users_in_db(db: &mut DatabaseInitializer) -> Result<(), diesel::result::Error> {
    use crate::schema::ftt_users::dsl::*;
    let encoder = Argon2PasswordEncoder::new();

    let conn = connection(db);
    let test_pwd = encoder.encode("test");
    let admin_pwd = encoder.encode("admin");
    let guest_pwd = encoder.encode("guest");
    let seed_users = [
        ("test", "test@example.local", &test_pwd),
        ("admin", "admin@example.local", &admin_pwd),
        ("guest", "guest@example.local", &guest_pwd),
    ];

    for (seed_name, seed_email, seed_password) in seed_users {
        let existing = ftt_users
            .filter(name.eq(seed_name).or(email.eq(seed_email)))
            .select(id)
            .first::<i32>(conn)
            .optional()?;

        if existing.is_none() {
            diesel::insert_into(ftt_users)
                .values(&NewUser {
                    name: seed_name,
                    email: seed_email,
                    password: &seed_password,
                })
                .execute(conn)?;
        }
    }

    Ok(())
}

pub fn get_all_users_from_db(db: &mut DatabaseInitializer) -> Option<Vec<DbUser>> {
    use crate::schema::ftt_users::dsl::*;

    let conn = connection(db);

    ftt_users
        .select(DbUser::as_select())
        .load(conn)
        .optional()
        .ok()?
}

pub fn list_users_in_db(
    db: &mut DatabaseInitializer,
) -> Result<Vec<UserInfo>, diesel::result::Error> {
    use crate::schema::ftt_users::dsl::*;

    let rows = ftt_users
        .order(id.asc())
        .select(DbUser::as_select())
        .load::<DbUser>(connection(db))?;

    Ok(rows.into_iter().map(UserInfo::from).collect())
}

pub fn get_user_in_db(
    db: &mut DatabaseInitializer,
    user_id: i32,
) -> Result<Option<UserInfo>, diesel::result::Error> {
    use crate::schema::ftt_users::dsl::*;

    let user = ftt_users
        .filter(id.eq(user_id))
        .select(DbUser::as_select())
        .first::<DbUser>(connection(db))
        .optional()?;

    Ok(user.map(UserInfo::from))
}

/// Looks a user up by name. This performs **no** password check: credentials are
/// verified by the security middleware (`authenticator::authenticate_basic`, via
/// `PasswordEncoder::matches`, or `authenticate_jwt`) before any handler taking an
/// `AuthenticatedUser` extractor runs.
///
/// Do not reintroduce a `password.eq(..)` filter here. The column stores randomly
/// salted Argon2 hashes, so string equality can only ever match a hash against
/// itself — never a password against its hash. That filter used to make every
/// freshly registered account fail login until the next server restart.
pub fn find_user_by_name_in_db(
    db: &mut DatabaseInitializer,
    user_name: &str,
) -> Result<Option<UserInfo>, diesel::result::Error> {
    use crate::schema::ftt_users::dsl::*;

    let user = ftt_users
        .filter(name.eq(user_name))
        .select(DbUser::as_select())
        .first::<DbUser>(connection(db))
        .optional()?;

    Ok(user.map(UserInfo::from))
}

impl From<diesel::result::Error> for CreateUserError {
    fn from(e: diesel::result::Error) -> Self {
        CreateUserError::DatabaseError(e)
    }
}

/// Creates a new user in ftt_users if no existing row shares the same name or email.
/// Returns the created user's info on success, or a `CreateUserError` on failure.
///
/// Takes the password **already encoded** rather than an encoder, so the caller can
/// persist the very same hash it puts in the in-memory user store. Hashing twice
/// yields two different salted digests, which used to desynchronise the two.
pub fn create_user_in_db(
    db: &mut DatabaseInitializer,
    new_user: &CreateUser,
    encoded_password: &str,
) -> Result<UserInfo, CreateUserError> {
    use crate::schema::ftt_users::dsl::*;

    let conn = connection(db);

    // Reject if name or email is already taken
    let existing = ftt_users
        .filter(name.eq(&new_user.name).or(email.eq(&new_user.email)))
        .select(DbUser::as_select())
        .first(conn)
        .optional()?;

    if existing.is_some() {
        return Err(CreateUserError::AlreadyExists);
    }

    // Insert and return the newly created row
    let inserted_user: DbUser = diesel::insert_into(ftt_users)
        .values(&NewUser {
            name: &new_user.name,
            email: &new_user.email,
            password: encoded_password,
        })
        .returning(DbUser::as_returning())
        .get_result(conn)?;

    Ok(UserInfo::from(inserted_user))
}

/// Update user profile.
/// Updates only bio and/or avatar since the rest isn't mutable per our design
pub fn update_user_profile_in_db(
    db: &mut DatabaseInitializer,
    user_id: i32,
    new_bio: Option<&str>,
    new_avatar_url: Option<&str>,
) -> Result<Option<UserInfo>, diesel::result::Error> {
    // Pull diesel schemas in scope 
    use crate::schema::ftt_users::dsl::*;

    // check if there is what to change
    if new_bio.is_none() && new_avatar_url.is_none() {
        return get_user_in_db(db, user_id);
    }

    diesel::update(ftt_users.filter(id.eq(user_id)))
        .set((
            new_bio.map(|value| bio.eq(value)),
            new_avatar_url.map(|value| avatar_url.eq(value)),
        ))
        .returning(DbUser::as_returning())
        .get_result::<DbUser>(connection(db))
        .optional()
        // Option<DbUser> --> Option<UserInfo>
        .map(|row| row.map(UserInfo::from))
}

pub fn find_user_id_by_name(
    db: &mut DatabaseInitializer,
    user_name: &str,
) -> Result<Option<i32>, diesel::result::Error> {
    use crate::schema::ftt_users::dsl as users;

    users::ftt_users
        .filter(users::name.eq(user_name))
        .select(users::id)
        .first::<i32>(connection(db))
        .optional()
}

/// Reasons why a friendlist mutation will not apply
///
/// `Option<UserInfo>` is insufficient -> None could mean "no such user"
/// or "there was a race on the column" eg someone made two concurrent
/// different changes at once
pub enum FriendlistUpdateError {
    /// The user to be befriended does not exist
    NotFound,
    /// You can't befriend yourself
    SelfReference,
    /// A race occured - best for the client to just try again.
    Conflict,
    /// An unforeseen DB error
    DatabaseError(diesel::result::Error),
}

impl From<diesel::result::Error> for FriendlistUpdateError {
    fn from(e: diesel::result::Error) -> Self {
        FriendlistUpdateError::DatabaseError(e)
    }
}

/// Adds friend to list. Returns `None` if no change happened
fn add_friend_to_list(list: &[i32], friend: i32) -> Option<Vec<i32>> {
    if list.contains(&friend) {
        return None;
    }

    let mut new = list.to_vec();
    new.push(friend);
    Some(new)
}

/// Returns `None` if exfriend was not in the list to begin with
fn remove_exfriend_from_list(list: &[i32], exfriend: i32) -> Option<Vec<i32>> {
    if !list.contains(&exfriend) {
        return None;
    }

    let new: Vec<i32> = list.iter().copied().filter(|id| *id != exfriend).collect();
    Some(new)
}

fn update_friendlist_in_db(
    db: &mut DatabaseInitializer,
    user_id: i32,
    other_id: i32,
    apply: fn(&[i32], i32) -> Option<Vec<i32>>,
) -> Result<UserInfo, FriendlistUpdateError> {
    use crate::schema::ftt_users::dsl::*;

    if user_id == other_id {
        return Err(FriendlistUpdateError::SelfReference);
    }

    let conn = connection(db);

    let current = ftt_users
        .filter(id.eq(user_id))
        .select(DbUser::as_select())
        .first::<DbUser>(conn)
        .optional()?
        .ok_or(FriendlistUpdateError::NotFound)?;

    let other_exists = ftt_users
        .filter(id.eq(other_id))
        .select(id)
        .first::<i32>(conn)
        .optional()?
        .is_some();

    if !other_exists {
        return Err(FriendlistUpdateError::NotFound);
    }

    // The `else` arm is the idempotency exercise - when the user already
    // has `other` in friendlist nothing happens.
    let Some(new) = apply(&current.friends.0, other_id) else {
        return Ok(UserInfo::from(current));
    };

    diesel::update(
        ftt_users
            .filter(id.eq(user_id))
            .filter(friends.eq(current.friends.clone())),
    )
    .set(friends.eq(FriendList(new)))
    .returning(DbUser::as_returning())
    .get_result::<DbUser>(conn)
    .optional()?
    .map(UserInfo::from)
    .ok_or(FriendlistUpdateError::Conflict)
}

pub fn befriend_in_db(
    db: &mut DatabaseInitializer,
    user_id: i32,
    friend_id: i32,
) -> Result<UserInfo, FriendlistUpdateError> {
    update_friendlist_in_db(db, user_id, friend_id, add_friend_to_list)
}

pub fn unfriend_in_db(
    db: &mut DatabaseInitializer,
    user_id: i32,
    exfriend_id: i32,
) -> Result<UserInfo, FriendlistUpdateError> {
    update_friendlist_in_db(db, user_id, exfriend_id, remove_exfriend_from_list)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn adding_a_new_friend_appends_it() {
        assert_eq!(add_friend_to_list(&[1, 2], 3), Some(vec![1, 2, 3]));
    }

    #[test]
    fn adding_an_existing_friend_is_a_no_op() {
        assert_eq!(add_friend_to_list(&[1, 2], 2), None);
    }

    #[test]
    fn adding_to_an_empty_list_works() {
        assert_eq!(add_friend_to_list(&[], 7), Some(vec![7]));
    }

    #[test]
    fn removing_a_friend_drops_only_that_one() {
        assert_eq!(remove_exfriend_from_list(&[1, 2, 3], 2), Some(vec![1, 3]));
    }

    #[test]
    fn removing_an_absent_friend_is_a_no_op() {
        assert_eq!(remove_exfriend_from_list(&[1, 2], 9), None);
    }

    #[test]
    fn removing_from_an_empty_list_is_a_no_op() {
        assert_eq!(remove_exfriend_from_list(&[], 1), None);
    }

    /// The column should never hold duplicates, but if one ever got in,
    /// removing must clear every copy rather than leave a stale one behind.
    #[test]
    fn removing_clears_every_duplicate() {
        assert_eq!(remove_exfriend_from_list(&[1, 2, 2, 3], 2), Some(vec![1, 3]));
    }
}
