// Copyright (c) 2026, ft_transcendence (https://42.fr) and/or its affiliates. All rights reserved

use crate::model::database_initializer::DatabaseInitializer;
use crate::users::{CreateUser, LoginUser, UserInfo};
use diesel::prelude::*;

// Internal Diesel model mapped to the ftt_users table
#[derive(Queryable, Selectable)]
#[diesel(table_name = crate::schema::ftt_users)]
#[diesel(check_for_backend(diesel::pg::Pg))]
struct User {
    id: i32,
    name: String,
    email: String,
}

// Used only for INSERT statements — no id field since it is generated by the DB
#[derive(Insertable)]
#[diesel(table_name = crate::schema::ftt_users)]
struct NewUser<'a> {
    name: &'a str,
    email: &'a str,
    password: &'a str,
}

pub enum CreateUserError {
    /// A user with the same name or email already exists
    AlreadyExists,
    /// An unexpected database error occurred
    DatabaseError(diesel::result::Error),
}

fn public_user(user: User) -> UserInfo {
    UserInfo {
        id: user.id,
        name: user.name,
        email: user.email,
        bio: "No profile info yet.".to_string(),
        avatar_url: "/images/profile.png".to_string(),
        status: "offline".to_string(),
    }
}

fn connection(db: &mut DatabaseInitializer) -> &mut PgConnection {
    db.connection
        .as_mut()
        .expect("Database connection is not established")
}

pub fn seed_users_in_db(db: &mut DatabaseInitializer) -> Result<(), diesel::result::Error> {
    use crate::schema::ftt_users::dsl::*;

    let conn = connection(db);
    let seed_users = [
        ("test", "test@example.local", "test"),
        ("admin", "admin@example.local", "admin"),
        ("guest", "guest@example.local", "guest"),
    ];

    for (seed_name, seed_email, seed_password) in seed_users {
        let existing = ftt_users
            .filter(name.eq(seed_name).or(email.eq(seed_email)))
            .select(id)
            .first::<i32>(conn)
            .optional()?;

        if existing.is_none() {
            diesel::insert_into(ftt_users)
                .values(&NewUser {
                    name: seed_name,
                    email: seed_email,
                    password: seed_password,
                })
                .execute(conn)?;
        }
    }

    Ok(())
}

pub fn list_users_in_db(
    db: &mut DatabaseInitializer,
) -> Result<Vec<UserInfo>, diesel::result::Error> {
    use crate::schema::ftt_users::dsl::*;

    let rows = ftt_users
        .order(id.asc())
        .select(User::as_select())
        .load::<User>(connection(db))?;

    Ok(rows.into_iter().map(public_user).collect())
}

pub fn get_user_in_db(
    db: &mut DatabaseInitializer,
    user_id: i32,
) -> Result<Option<UserInfo>, diesel::result::Error> {
    use crate::schema::ftt_users::dsl::*;

    let user = ftt_users
        .filter(id.eq(user_id))
        .select(User::as_select())
        .first::<User>(connection(db))
        .optional()?;

    Ok(user.map(public_user))
}

pub fn login_user_in_db(
    db: &mut DatabaseInitializer,
    login: &LoginUser,
) -> Result<Option<UserInfo>, diesel::result::Error> {
    use crate::schema::ftt_users::dsl::*;

    let user = ftt_users
        .filter(name.eq(&login.name).and(password.eq(&login.password)))
        .select(User::as_select())
        .first::<User>(connection(db))
        .optional()?;

    Ok(user.map(public_user))
}

impl From<diesel::result::Error> for CreateUserError {
    fn from(e: diesel::result::Error) -> Self {
        CreateUserError::DatabaseError(e)
    }
}

/// Creates a new user in ftt_users if no existing row shares the same name or email.
/// Returns the created user's info on success, or a `CreateUserError` on failure.
pub fn create_user_in_db(
    db: &mut DatabaseInitializer,
    new_user: &CreateUser,
) -> Result<UserInfo, CreateUserError> {
    use crate::schema::ftt_users::dsl::*;

    let conn = connection(db);

    // Reject if name or email is already taken
    let existing = ftt_users
        .filter(name.eq(&new_user.name).or(email.eq(&new_user.email)))
        .select(User::as_select())
        .first(conn)
        .optional()?;

    if existing.is_some() {
        return Err(CreateUserError::AlreadyExists);
    }

    // Insert and return the newly created row
    let inserted: User = diesel::insert_into(ftt_users)
        .values(&NewUser {
            name: &new_user.name,
            email: &new_user.email,
            password: &new_user.password,
        })
        .returning(User::as_returning())
        .get_result(conn)?;

    Ok(public_user(inserted))
}
